import Heading, { HeadingSize } from '@/components/Heading'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Single-page developer portfolio</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
      </Head>
      <main>
        <Heading size={HeadingSize.xl}>Heading (XL)</Heading>
        <Heading size={HeadingSize.l}>HTML</Heading>
      </main>
    </>
  )
}
